FROM mcr.microsoft.com/windows/servercore:ltsc2022
RUN powershell -Command \
    $ProgressPreference = 'SilentlyContinue'; \
    Invoke-WebRequest https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe -OutFile python-installer.exe; \
    .\python-installer.exe /quiet InstallAllUsers=1 PrependPath=1; \
    del python-installer.exe
RUN pip install --no-cache-dir pyinstaller==6.1.0
WORKDIR /build
COPY discord.py .
RUN pyinstaller --onefile --console --distpath . discord.py
